export default {
  white: '#ffffff',
  black: '#3F414E',
  darkBlack: '#1b1c22',
  gray: '#A1A4B2',
  accent: '#8E97FD',
  secondary: '#F2F3F7',
  primaryForeground: '#FFECCC',
  secondaryForeground: '#EBEAEC',
  error: '#FA6E5A',
  grayForeground: '#fbfaf7',
  timePickerForeground: '#f5f5f9',
  lightSalmon: '#FFC97E',
  darkGray: '#333242',
  lightGreen: '#84C6AE',
  lightYellow: '#FEDEA5',
  lightAccent: '#E4E6FD',
  accentForeground: '#ADB8D9',
  calm: '#f4dccd',
  music: '#FAF7F2',
  border: '#BABCC6',
  grayPlayer: '#A0A3B1',
  red: '#FF84A2',
  blue: '#03174C',
  sleep: '#E6E7F2',
  sleepCard: '#FFE7BF',
  sleepFilter: '#586894',
  divider: '#98A1BD',
};

export const cardsColor = {
  stress: '#8E97FD',
  performance: '#FA6E5A',
  happiness: '#FEB18F',
  anxiety: '#FFCF86',
  growth: '#6CB28E',
  sleep: '#3F414E',
  text: {
    stress: '#FEF9F3',
    performance: '#FEF9F3',
    happiness: '#3F414E',
    anxiety: '#3F414E',
    growth: '#FEF9F3',
    sleep: '#EBEAEC',
  },
};
